x-schemaspy-base: &schemaspy-base
  build: .
  image: schemaspy_custom:latest
  command:
    - -configFile
    - /schemaspy.properties
    - -dp
    - /drivers/jdbc-4.50.11.jar
    - -meta
    - /metadata/schema.meta.xml
    - -error

services:
  schemaspy_analytics:
    <<: *schemaspy-base
    container_name: informix-schemaspy-analytics
    env_file:
      - ./db/db-analytics/env/.env
    volumes:
      - ./drivers:/drivers
      - ./properties/schemaspy.properties.template:/schemaspy.properties.template
      - ./output/analytics:/output
      - ./db/db-analytics/metadata:/metadata